name: Matrix workflow Demo

on: push

jobs:
  build:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-systems: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.operating-systems }}

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
